format_version: 4
pipelines:
  prod-table-app-lint-test-build:
    group: ecosystem
    label_template: ${git[:7]}
    lock_behavior: none
    display_order: 115
    materials:
      git:
        git: git@github.com:contentstack/marketplace-table-app
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - lint-test-build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            roles:
              - devops
            allow_only_on_success: true
          secure_variables:
            REACT_APP_TRACKER_TOKEN: AES:BbhblE188VzWdo/uw1lxoA==:HRbvYwiOm6KqDPerkU+UPv8ckXc/Hyi7z8ZJJx4b6qng2vESeM3povP32Y8D4lAf
            REACT_APP_TRACKER_ENV: AES:bWcAg9Bvo/gR6DAErS3qGQ==:nP9hsoxcxJ6ofMt5bPGrlHRzIpPKJMeY4Yr72kEc9pE=
            REACT_APP_MIXPANEL_TOKEN: AES:zTroDzGouDM2UsTBtW+aiw==:vk3bQOuZSKmAoghqfTqfwlPNPiHEwtBT42FNI2iTQbpzqQjK37fcb3F+JtG1yVsg
          jobs:
            lint-test-build:
              elastic_profile_id: k8s-cicd-publish-npm-package
              timeout: 0
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    arguments:
                      - -c 
                      - echo //npm.pkg.github.com/:_authToken=$GITHUB_PERSONAL_ACCESS_TOKEN > .npmrc
                    command: sh
                - exec:
                    arguments:
                      - -c 
                      - echo "@contentstack:registry=https://npm.pkg.github.com/contentstack" >> .npmrc
                    command: sh               
                - exec:
                    arguments:
                      - install
                    command: npm
                - exec:
                    arguments:
                      - -c
                      - "export CI='' && npm run build"
                    command: sh
