format_version: 4
pipelines:
  prod-table-app-deploy:
    group: ecosystem
    label_template: "${prod-table-app-build}"
    lock_behavior: none
    display_order: 116
    materials:
      prod-table-app-build:
        pipeline: prod-table-app-lint-test-build
        stage: lint-test-build
    stages:
      - prod-deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: yes
          approval:
            type: manual
            roles:
              - devops
            allow_only_on_success: true 
          jobs:
            prod-deploy:
              elastic_profile_id: prod-ecosystem-aws-cli
              timeout: 0
              tasks:
                - fetch:
                    pipeline: prod-table-app-lint-test-build
                    stage: lint-test-build
                    job: lint-test-build
                    source: build/
                    is_file: no
                    destination: ./
                - exec:
                    arguments:
                      - -c
                      - aws s3 cp build s3://prod-table-app --recursive
                    command: sh
                - exec:
                    arguments:
                      - -c
                      - aws cloudfront create-invalidation --distribution-id E2I42R07YO13W7 --paths "/*"
                    command: sh
