format_version: 4
pipelines:
  stag-table-app-deploy:
    group: ecosystem
    label_template: "${stag-table-app-build}"
    lock_behavior: none
    display_order: 114
    parameters:
      E2E_TESTS_REPO_URL: git@github.com:contentstack/marketplace-table-app.git
      E2E_TESTS_REPO_BRANCH: staging
    materials:
      stag-table-app-build:
        pipeline: stag-table-app-lint-test-build
        stage: lint-test-build
    stages:
      - stag-deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: yes
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            stag-deploy:
              elastic_profile_id: nonprod-ecosystem-aws-cli
              timeout: 0
              tasks:
                - fetch:
                    pipeline: stag-table-app-lint-test-build
                    stage: lint-test-build
                    job: lint-test-build
                    source: build/
                    is_file: no
                    destination: ./
                - exec:
                    arguments:
                      - -c
                      - aws s3 cp build s3://stag-table-app --recursive
                    command: sh
                - exec:
                    arguments:
                      - -c
                      - aws cloudfront create-invalidation --distribution-id E1FCDW374UGM5Q --paths "/*"
                    command: sh
