format_version: 4
pipelines:
  stag-table-app-lint-test-build:
    group: ecosystem
    label_template: ${git[:7]}
    lock_behavior: none
    display_order: 113
    materials:
      git:
        git: git@github.com:contentstack/marketplace-table-app
        shallow_clone: false
        auto_update: true
        branch: staging
    stages:
      - lint-test-build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          secure_variables:
            REACT_APP_TRACKER_TOKEN: AES:0fOA64XJhj0QBX3cAUnncg==:tOoJbUVrdmGnnSYaDqCC5+aSvugRO3P+FRSDZyPNUYaLzehffalSDeJ8+zuMe2t5
            REACT_APP_TRACKER_ENV: AES:pkcVyzi1Mrd2ljsF6E43MA==:5Sxi0bzRj4yei3gOpkejoxCKCCpZjbdGW4KrnFK9z0Y=
            REACT_APP_MIXPANEL_TOKEN: AES:wAYgcwxAIxuHB5UKDZbSTw==:uLrUaVh4ydn/U9m29dX2NVLdYt480MxlZIpY8aNNwFMxZlcXbBPqZK33Qok/2tME
          jobs:
            lint-test-build:
              elastic_profile_id: k8s-cicd-publish-npm-package
              timeout: 0
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    arguments:
                      - -c 
                      - echo //npm.pkg.github.com/:_authToken=$GITHUB_PERSONAL_ACCESS_TOKEN > .npmrc
                    command: sh
                - exec:
                    arguments:
                      - -c 
                      - echo "@contentstack:registry=https://npm.pkg.github.com/contentstack" >> .npmrc
                    command: sh               
                - exec:
                    arguments:
                      - install
                    command: npm
                - exec:
                    arguments:
                      - -c
                      - "export CI='' && export SKIP_PREFLIGHT_CHECK=true && npm run build"
                    command: sh
